// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Taller_TIC1_Backend.Data;

#nullable disable

namespace Taller_TIC1_Backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250913172827_FixIdentityColumns")]
    partial class FixIdentityColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Taller_TIC1_Backend.Models.CEmpresa", b =>
                {
                    b.Property<int>("IdCliente")
                        .HasColumnType("integer")
                        .HasColumnName("idCliente");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<long>("Nit")
                        .HasColumnType("bigint")
                        .HasColumnName("nit");

                    b.Property<string>("RepresentanteLegal")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("representante");

                    b.HasKey("IdCliente");

                    b.HasIndex("ClienteId");

                    b.ToTable("CEmpresa", (string)null);
                });

            modelBuilder.Entity("Taller_TIC1_Backend.Models.CNatural", b =>
                {
                    b.Property<int>("IdCliente")
                        .HasColumnType("integer")
                        .HasColumnName("idCliente");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("apellido");

                    b.Property<long>("Cedula")
                        .HasColumnType("bigint")
                        .HasColumnName("cedula");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("integer");

                    b.HasKey("IdCliente");

                    b.HasIndex("ClienteId");

                    b.ToTable("CNatural", (string)null);
                });

            modelBuilder.Entity("Taller_TIC1_Backend.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<int>("IdVehiculo")
                        .HasColumnType("integer")
                        .HasColumnName("idVehiculo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nombre");

                    b.Property<long>("Telefono")
                        .HasColumnType("bigint")
                        .HasColumnName("telefono");

                    b.Property<int?>("VehiculoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdVehiculo");

                    b.HasIndex("VehiculoId");

                    b.ToTable("Cliente", (string)null);
                });

            modelBuilder.Entity("Taller_TIC1_Backend.Models.DetalleReparacion", b =>
                {
                    b.Property<int>("IdServicio")
                        .HasColumnType("integer")
                        .HasColumnName("idServicio");

                    b.Property<int>("IdDetalleReparacionRepuesto")
                        .HasColumnType("integer")
                        .HasColumnName("idDetalleReparacionRepuesto");

                    b.HasKey("IdServicio");

                    b.HasIndex("IdDetalleReparacionRepuesto");

                    b.ToTable("DetalleReparacion", (string)null);
                });

            modelBuilder.Entity("Taller_TIC1_Backend.Models.DetalleReparacionRepuesto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<int>("IdRepuesto")
                        .HasColumnType("integer")
                        .HasColumnName("idRepuesto");

                    b.HasKey("Id");

                    b.HasIndex("IdRepuesto");

                    b.ToTable("DetalleReparacionRepuesto", (string)null);
                });

            modelBuilder.Entity("Taller_TIC1_Backend.Models.DetalleRevision", b =>
                {
                    b.Property<int>("IdServicio")
                        .HasColumnType("integer")
                        .HasColumnName("idServicio");

                    b.Property<string>("Detalles")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("detalles");

                    b.HasKey("IdServicio");

                    b.ToTable("DetalleRevision", (string)null);
                });

            modelBuilder.Entity("Taller_TIC1_Backend.Models.DetalleServicioOrden", b =>
                {
                    b.Property<int>("IdOrdenTrabajo")
                        .HasColumnType("integer")
                        .HasColumnName("idOrdenTrabajo");

                    b.Property<int>("IdServicio")
                        .HasColumnType("integer")
                        .HasColumnName("idServicio");

                    b.HasKey("IdOrdenTrabajo", "IdServicio");

                    b.HasIndex("IdServicio");

                    b.ToTable("DetalleServicioOrden", (string)null);
                });

            modelBuilder.Entity("Taller_TIC1_Backend.Models.Empleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("apellido");

                    b.Property<long>("Cedula")
                        .HasColumnType("bigint")
                        .HasColumnName("cedula");

                    b.Property<DateTime>("FechaContratacion")
                        .HasColumnType("date")
                        .HasColumnName("fechaContratacion");

                    b.Property<int>("IdTipoEmpleado")
                        .HasColumnType("integer")
                        .HasColumnName("idTipoEmpleado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nombre");

                    b.Property<double>("Salario")
                        .HasColumnType("double precision")
                        .HasColumnName("salario");

                    b.Property<int?>("TipoEmpleadoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdTipoEmpleado");

                    b.HasIndex("TipoEmpleadoId");

                    b.ToTable("Empleado", (string)null);
                });

            modelBuilder.Entity("Taller_TIC1_Backend.Models.EstadoServicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("descripcion");

                    b.HasKey("Id");

                    b.ToTable("EstadoServicio", (string)null);
                });

            modelBuilder.Entity("Taller_TIC1_Backend.Models.OrdenDeTrabajo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("date")
                        .HasColumnName("fechaCreacion");

                    b.Property<int>("IdTipoEstadoOrden")
                        .HasColumnType("integer")
                        .HasColumnName("idTipoEstadoOrden");

                    b.Property<int?>("TipoEstadoOrdenId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdTipoEstadoOrden");

                    b.HasIndex("TipoEstadoOrdenId");

                    b.ToTable("OrdenTrabajo", (string)null);
                });

            modelBuilder.Entity("Taller_TIC1_Backend.Models.Proveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Contacto")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("contacto");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("Proveedor", (string)null);
                });

            modelBuilder.Entity("Taller_TIC1_Backend.Models.Repuesto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nombre");

                    b.Property<long>("Numero_serie")
                        .HasColumnType("bigint")
                        .HasColumnName("numero_serie");

                    b.Property<float>("Precio")
                        .HasColumnType("real")
                        .HasColumnName("precio");

                    b.Property<int>("Stock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("stock");

                    b.HasKey("Id");

                    b.ToTable("Repuesto", (string)null);
                });

            modelBuilder.Entity("Taller_TIC1_Backend.Models.RepuestoProveedor", b =>
                {
                    b.Property<int>("IdRepuesto")
                        .HasColumnType("integer")
                        .HasColumnName("idRepuesto");

                    b.Property<int>("IdProveedor")
                        .HasColumnType("integer")
                        .HasColumnName("idProveedor");

                    b.HasKey("IdRepuesto", "IdProveedor");

                    b.HasIndex("IdProveedor");

                    b.ToTable("RepuestoProveedor", (string)null);
                });

            modelBuilder.Entity("Taller_TIC1_Backend.Models.Servicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<float>("Costo")
                        .HasColumnType("real")
                        .HasColumnName("costo");

                    b.Property<int?>("EmpleadoId")
                        .HasColumnType("integer");

                    b.Property<int?>("EstadoId")
                        .HasColumnType("integer");

                    b.Property<int>("IdCliente")
                        .HasColumnType("integer")
                        .HasColumnName("idCliente");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("integer")
                        .HasColumnName("idEmpleado");

                    b.Property<int>("IdEstado")
                        .HasColumnType("integer")
                        .HasColumnName("idEstado");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("EstadoId");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdEmpleado");

                    b.HasIndex("IdEstado");

                    b.ToTable("Servicio", (string)null);
                });

            modelBuilder.Entity("Taller_TIC1_Backend.Models.Taller", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("direccion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("Taller", (string)null);
                });

            modelBuilder.Entity("Taller_TIC1_Backend.Models.TipoEmpleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("descripcion");

                    b.HasKey("Id");

                    b.ToTable("TipoEmpleado", (string)null);
                });

            modelBuilder.Entity("Taller_TIC1_Backend.Models.TipoEstadoOrden", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("descripcion");

                    b.HasKey("Id");

                    b.ToTable("TipoEstadoOrden", (string)null);
                });

            modelBuilder.Entity("Taller_TIC1_Backend.Models.UsuarioClienteTaller", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("contrasena");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<int>("IdCliente")
                        .HasColumnType("integer")
                        .HasColumnName("idCliente");

                    b.Property<int>("IdTaller")
                        .HasColumnType("integer")
                        .HasColumnName("idTaller");

                    b.HasKey("Id");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdTaller");

                    b.ToTable("UsuariosClienteTaller", (string)null);
                });

            modelBuilder.Entity("Taller_TIC1_Backend.Models.UsuarioEmpleadoTaller", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("contrasena");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("integer")
                        .HasColumnName("idEmpleado");

                    b.Property<int>("IdTaller")
                        .HasColumnType("integer")
                        .HasColumnName("idTaller");

                    b.HasKey("Id");

                    b.HasIndex("IdEmpleado");

                    b.HasIndex("IdTaller");

                    b.ToTable("UsuariosEmpleadoTaller", (string)null);
                });

            modelBuilder.Entity("Taller_TIC1_Backend.Models.VElectrico", b =>
                {
                    b.Property<int>("IdVehiculo")
                        .HasColumnType("integer")
                        .HasColumnName("idVehiculo");

                    b.Property<int>("CapacidadBateria")
                        .HasColumnType("integer")
                        .HasColumnName("capacidadBateria");

                    b.Property<int?>("VehiculoId")
                        .HasColumnType("integer");

                    b.HasKey("IdVehiculo");

                    b.HasIndex("VehiculoId");

                    b.ToTable("VElectrico", (string)null);
                });

            modelBuilder.Entity("Taller_TIC1_Backend.Models.VGasolina", b =>
                {
                    b.Property<int>("IdVehiculo")
                        .HasColumnType("integer")
                        .HasColumnName("idVehiculo");

                    b.Property<int>("Cilindraje")
                        .HasColumnType("integer")
                        .HasColumnName("cilindraje");

                    b.Property<int?>("VehiculoId")
                        .HasColumnType("integer");

                    b.HasKey("IdVehiculo");

                    b.HasIndex("VehiculoId");

                    b.ToTable("VGasolina", (string)null);
                });

            modelBuilder.Entity("Taller_TIC1_Backend.Models.VHibrido", b =>
                {
                    b.Property<int>("IdVehiculo")
                        .HasColumnType("integer")
                        .HasColumnName("idVehiculo");

                    b.Property<int>("CapacidadBateria")
                        .HasColumnType("integer")
                        .HasColumnName("capacidadBateria");

                    b.Property<int>("Cilindraje")
                        .HasColumnType("integer")
                        .HasColumnName("cilindraje");

                    b.Property<int?>("VehiculoId")
                        .HasColumnType("integer");

                    b.HasKey("IdVehiculo");

                    b.HasIndex("VehiculoId");

                    b.ToTable("VHibrido", (string)null);
                });

            modelBuilder.Entity("Taller_TIC1_Backend.Models.Vehiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Año")
                        .HasColumnType("integer")
                        .HasColumnName("anio");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("marca");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("modelo");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("placa");

                    b.HasKey("Id");

                    b.ToTable("Vehiculo", (string)null);
                });

            modelBuilder.Entity("Taller_TIC1_Backend.Models.CEmpresa", b =>
                {
                    b.HasOne("Taller_TIC1_Backend.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId");

                    b.HasOne("Taller_TIC1_Backend.Models.Cliente", null)
                        .WithOne()
                        .HasForeignKey("Taller_TIC1_Backend.Models.CEmpresa", "IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Taller_TIC1_Backend.Models.CNatural", b =>
                {
                    b.HasOne("Taller_TIC1_Backend.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId");

                    b.HasOne("Taller_TIC1_Backend.Models.Cliente", null)
                        .WithOne()
                        .HasForeignKey("Taller_TIC1_Backend.Models.CNatural", "IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Taller_TIC1_Backend.Models.Cliente", b =>
                {
                    b.HasOne("Taller_TIC1_Backend.Models.Vehiculo", null)
                        .WithMany()
                        .HasForeignKey("IdVehiculo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Taller_TIC1_Backend.Models.Vehiculo", "Vehiculo")
                        .WithMany()
                        .HasForeignKey("VehiculoId");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("Taller_TIC1_Backend.Models.DetalleReparacion", b =>
                {
                    b.HasOne("Taller_TIC1_Backend.Models.DetalleReparacionRepuesto", null)
                        .WithMany()
                        .HasForeignKey("IdDetalleReparacionRepuesto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Taller_TIC1_Backend.Models.Servicio", null)
                        .WithOne()
                        .HasForeignKey("Taller_TIC1_Backend.Models.DetalleReparacion", "IdServicio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Taller_TIC1_Backend.Models.DetalleReparacionRepuesto", b =>
                {
                    b.HasOne("Taller_TIC1_Backend.Models.Repuesto", null)
                        .WithMany()
                        .HasForeignKey("IdRepuesto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Taller_TIC1_Backend.Models.DetalleRevision", b =>
                {
                    b.HasOne("Taller_TIC1_Backend.Models.Servicio", null)
                        .WithOne()
                        .HasForeignKey("Taller_TIC1_Backend.Models.DetalleRevision", "IdServicio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Taller_TIC1_Backend.Models.DetalleServicioOrden", b =>
                {
                    b.HasOne("Taller_TIC1_Backend.Models.OrdenDeTrabajo", null)
                        .WithMany()
                        .HasForeignKey("IdOrdenTrabajo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Taller_TIC1_Backend.Models.Servicio", null)
                        .WithMany()
                        .HasForeignKey("IdServicio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Taller_TIC1_Backend.Models.Empleado", b =>
                {
                    b.HasOne("Taller_TIC1_Backend.Models.TipoEmpleado", null)
                        .WithMany()
                        .HasForeignKey("IdTipoEmpleado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Taller_TIC1_Backend.Models.TipoEmpleado", "TipoEmpleado")
                        .WithMany()
                        .HasForeignKey("TipoEmpleadoId");

                    b.Navigation("TipoEmpleado");
                });

            modelBuilder.Entity("Taller_TIC1_Backend.Models.OrdenDeTrabajo", b =>
                {
                    b.HasOne("Taller_TIC1_Backend.Models.TipoEstadoOrden", null)
                        .WithMany()
                        .HasForeignKey("IdTipoEstadoOrden")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Taller_TIC1_Backend.Models.TipoEstadoOrden", "TipoEstadoOrden")
                        .WithMany()
                        .HasForeignKey("TipoEstadoOrdenId");

                    b.Navigation("TipoEstadoOrden");
                });

            modelBuilder.Entity("Taller_TIC1_Backend.Models.RepuestoProveedor", b =>
                {
                    b.HasOne("Taller_TIC1_Backend.Models.Proveedor", null)
                        .WithMany()
                        .HasForeignKey("IdProveedor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Taller_TIC1_Backend.Models.Repuesto", null)
                        .WithMany()
                        .HasForeignKey("IdRepuesto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Taller_TIC1_Backend.Models.Servicio", b =>
                {
                    b.HasOne("Taller_TIC1_Backend.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId");

                    b.HasOne("Taller_TIC1_Backend.Models.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId");

                    b.HasOne("Taller_TIC1_Backend.Models.EstadoServicio", "Estado")
                        .WithMany()
                        .HasForeignKey("EstadoId");

                    b.HasOne("Taller_TIC1_Backend.Models.Cliente", null)
                        .WithMany()
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Taller_TIC1_Backend.Models.Empleado", null)
                        .WithMany()
                        .HasForeignKey("IdEmpleado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Taller_TIC1_Backend.Models.EstadoServicio", null)
                        .WithMany()
                        .HasForeignKey("IdEstado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Empleado");

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("Taller_TIC1_Backend.Models.UsuarioClienteTaller", b =>
                {
                    b.HasOne("Taller_TIC1_Backend.Models.Cliente", null)
                        .WithMany()
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Taller_TIC1_Backend.Models.Taller", null)
                        .WithMany()
                        .HasForeignKey("IdTaller")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Taller_TIC1_Backend.Models.UsuarioEmpleadoTaller", b =>
                {
                    b.HasOne("Taller_TIC1_Backend.Models.Empleado", null)
                        .WithMany()
                        .HasForeignKey("IdEmpleado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Taller_TIC1_Backend.Models.Taller", null)
                        .WithMany()
                        .HasForeignKey("IdTaller")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Taller_TIC1_Backend.Models.VElectrico", b =>
                {
                    b.HasOne("Taller_TIC1_Backend.Models.Vehiculo", null)
                        .WithOne()
                        .HasForeignKey("Taller_TIC1_Backend.Models.VElectrico", "IdVehiculo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Taller_TIC1_Backend.Models.Vehiculo", "Vehiculo")
                        .WithMany()
                        .HasForeignKey("VehiculoId");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("Taller_TIC1_Backend.Models.VGasolina", b =>
                {
                    b.HasOne("Taller_TIC1_Backend.Models.Vehiculo", null)
                        .WithOne()
                        .HasForeignKey("Taller_TIC1_Backend.Models.VGasolina", "IdVehiculo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Taller_TIC1_Backend.Models.Vehiculo", "Vehiculo")
                        .WithMany()
                        .HasForeignKey("VehiculoId");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("Taller_TIC1_Backend.Models.VHibrido", b =>
                {
                    b.HasOne("Taller_TIC1_Backend.Models.Vehiculo", null)
                        .WithOne()
                        .HasForeignKey("Taller_TIC1_Backend.Models.VHibrido", "IdVehiculo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Taller_TIC1_Backend.Models.Vehiculo", "Vehiculo")
                        .WithMany()
                        .HasForeignKey("VehiculoId");

                    b.Navigation("Vehiculo");
                });
#pragma warning restore 612, 618
        }
    }
}
